version: '3'
services:
  nginx:
    container_name: v-nginx
    restart: always
    build:
      context: ./
      dockerfile: ./docker/nginx/web-Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./dist:/home/html/dist
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"

  mysql:
    container_name: v-mysql
    build:
      context: ./
      dockerfile: ./docker/mysql/mysql-Dockerfile
    environment:
      MYSQL_DATABASE: todo_s
      MYSQL_ROOT_PASSWORD: yaya123.
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Tokyo
    expose:
      - "3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    restart: always

  tomcat:
    container_name: v-tomcat
    restart: always
    build:
      context: ./
      dockerfile: ./docker/tomcat/api-Dockerfile
    working_dir: /usr/local/tomcat/bin/
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./docker/tomcat/api_code:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"                    
    depends_on:
      - mysql
